remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-include-cache

title: Bogdan Neterebskii
author: Bogdan Neterebskii


minimal_mistakes_skin    : "contrast" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-US"
title                    : "Bogdan Neterebskii"
title_separator          : "-"
subtitle                 : # site tagline that appears below site title in masthead
name                     : "Bogdan Neterebskii"
description              : "An amazing website."
url                      : "https://ozzzzz.github.io"
baseurl                  :  # "/content" # the subpath of your site, e.g. "/blog"
repository               : "ozzzzz/ozzzzz.github.io"
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo                     : # path of logo image to display in the masthead, e.g. "/assets/images/88x88.png"
masthead_title           : # overrides the website title displayed in the masthead, use " " for no title
# breadcrumbs            : false # true, false (default)
words_per_minute         : 200
comments:
  provider               : # false (default), "disqus", "discourse", "facebook", "staticman", "staticman_v2", "utterances", "giscus", "custom"
  disqus:
    shortname            : # https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    # https://developers.facebook.com/docs/plugins/comments
    appid                :
    num_posts            : # 5 (default)
    colorscheme          : # "light" (default), "dark"
  utterances:
    theme                : # "github-light" (default), "github-dark"
    issue_term           : # "pathname" (default)
  giscus:
    repo_id              : # Shown during giscus setup at https://giscus.app
    category_name        : # Full text name of the category
    category_id          : # Shown during giscus setup at https://giscus.app
    discussion_term      : # "pathname" (default), "url", "title", "og:title"
    reactions_enabled    : # '1' for enabled (default), '0' for disabled
    theme                : # "light" (default), "dark", "dark_dimmed", "transparent_dark", "preferred_color_scheme"
  staticman:
    branch               : # "master"
    endpoint             : # "https://{your Staticman v3 API}/v3/entry/github/"
reCaptcha:
  siteKey                :
  secret                 :
atom_feed:
  path                   : # blank (default) uses feed.xml
  hide                   : # true, false (default)
search                   : # true, false (default)
search_full_content      : # true, false (default)
search_provider          : # lunr (default), algolia, google
lunr:
  search_within_pages    : # true, false (default)
algolia:
  application_id         : # YOUR_APPLICATION_ID
  index_name             : # YOUR_INDEX_NAME
  search_only_api_key    : # YOUR_SEARCH_ONLY_API_KEY
  powered_by             : # true (default), false
google:
  search_engine_id       : # YOUR_SEARCH_ENGINE_ID
  instant_search         : # false (default), true
# SEO Related
google_site_verification :
bing_site_verification   :
naver_site_verification  :
yandex_site_verification :
baidu_site_verification  :

# Social Sharing
twitter:
  username               :
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 : # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles

# Analytics
analytics:
  provider               : false # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          :
    anonymize_ip         : # true, false (default)


# Site Author
author:
  name             : "Bogdan Neterebskii"
  avatar           : # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              : "I am an **amazing** person."
  location         : # ""
  email            :
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ozzzzz"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/bneterebskii/"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/bogdan-neterebskii-04a6958b/"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ozzzzz"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/bogdan_has_fun/"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/bogdan-neterebskii-04a6958b/"


# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path>/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path>/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/


# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development


# Defaults
defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true















# # ___________________________________

# # --- List of links in the navigation bar --- #

# navbar-links:
#   Resume | CV: "resume_cv"
#   # Resources:
#   #   - Beautiful Jekyll: "https://beautifuljekyll.com"
#   #   - Learn markdown: "https://www.markdowntutorial.com/"
#   # Author's home: "https://deanattali.com"

# # --- Logo --- #

# # Image to show in the navigation bar - works best with a square image
# # Remove this parameter if you don't want an image in the navbar
# avatar: "/assets/img/photo-squared.jpg"

# # By default, the image is cut into a circle. You can disable this behaviour by setting 'round-avatar: false'
# round-avatar: true

# # If you want to have an image logo in the top-left corner instead of having the title of the website,
# # then specify the following parameter
# #title-img: /path/to/image

# # --- Footer social media links --- #

# # Select the social network links that you want to show in the footer.
# # Uncomment the links you want to show and add your information to each one.
# social-network-links:
#   email: "bog2dan1@gmail.com"
#   facebook: bogdan.neterebskiy
#   github: ozzzzz
#   twitter: bonozzzzz
#   instagram: bneterebskii
#   linkedin: bogdan-neterebskii-04a6958b
# #  medium: yourname
# #  stackoverflow: ""
# #  spotify: yourname
# #  telegram: yourname
# #  calendly: yourname
# #  google-scholar: your google scholar

# # If you want to show a link to an RSS in the footer, add the site description here.
# # If you don't want to show an RSS link, remove the following line.
# # rss-description: This website is a virtual proof that I'm awesome

# # --- General options --- #

# # Select which social network share links to show in posts
# share-links-active:
#   email: true
#   twitter: true
#   github: true
#   linkedin: true
#   instagram: true
#   facebook: true

# # How to display the link to your website in the footer
# # Remove this if you don't want a link in the footer
# # url-pretty: "MyWebsite.com"

# # Excerpt word length - Truncate the excerpt of each post on the feed page to the specified number of words
# excerpt_length: 50

# # Whether or not to show an excerpt for every blog post in the feed page
# feed_show_excerpt: true

# # Whether or not to show a list of tags below each post preview in the feed page
# feed_show_tags: true

# # The keywords to associate with your website, for SEO purposes
# #keywords: "my,list,of,keywords"

# # --- Colours / background image --- #

# # Personalize the colours in your website. Colour values can be any valid CSS colour

# navbar-col: "#EAEAEA"
# navbar-text-col: "#404040"
# navbar-border-col: "#DDDDDD"
# page-col: "#FFFFFF"
# text-col: "#404040"
# link-col: "#008AFF"
# hover-col: "#0085A1"
# footer-col: "#EAEAEA"
# footer-text-col: "#777777"
# footer-link-col: "#404040"

# # Alternatively, the navbar, footer, and page background can be set to an image
# # instead of colour

# #navbar-img: "/assets/img/bgimage.png"
# #footer-img: "/assets/img/bgimage.png"
# #page-img: "/assets/img/bgimage.png"

# # Suggest a colour for mobile browsers to use as the browser's theme. This is only supported by a few mobile browsers.
# #mobile-theme-col: "#0085A1"

# # For any extra visual customization, you can include additional CSS files in every page on your site. List any custom CSS files here
# #site-css:
# #  - "/assets/css/custom-styles.css"

# # If you have common JavaScript files that should be included in every page, list them here
# #site-js:
# #  - "/assets/js/custom-script.js"

# # --- Web Analytics Section --- #

# # Fill in your Google Analytics gtag.js ID to track your website using gtag
# #gtag: ""

# # Fill in your Google Analytics ID to track your website using Google Analytics
# #google_analytics: ""

# # Fill in your Cloudflare Analytics beacon token to track your website using Cloudflare Analytics
# #cloudflare_analytics: ""

# # Google Tag Manager ID
# #gtm: ""

# # Matomo (aka Piwik) Web statistics
# # Uncomment the following section to enable Matomo. The opt-out parameter controls
# # whether or not you want to allow users to opt out of tracking.
# #matomo:
# #  site_id: "9"
# #  uri: "demo.wiki.pro"
# #  opt-out: true

# # --- Comments --- #

# # To use Disqus comments, sign up to https://disqus.com and fill in your Disqus shortname (NOT the userid)
# #disqus: ""

# # To use Facebook Comments, create a Facebook app and fill in the Facebook App ID
# #fb_comment_id: ""

# # To use Utterances comments: (0) uncomment the following section, (1) fill in
# # "repository" (make sure the repository is public), (2) Enable Issues in your repository,
# # (3) Install the Utterances app in your repository https://github.com/apps/utterances
# # See more details about the parameters below at https://utteranc.es/
# #utterances:
# #  repository: # GitHub username/repository eg. "daattali/beautiful-jekyll"
# #  issue-term: title   # Mapping between blog posts and GitHub issues
# #  theme: github-light # Utterances theme
# #  label: blog-comments # Label that will be assigned to GitHub Issues created by Utterances

# # To use Staticman comments, uncomment the following section. You may leave the reCaptcha
# # section commented if you aren't using reCaptcha for spam protection.
# # Using Staticman requires advanced knowledge, please consult
# # https://github.com/eduardoboucas/staticman/ and https://staticman.net/ for further
# # instructions. For any support with staticman please direct questions to staticman and
# # not to BeautifulJekyll.
# #staticman:
# #  repository : # GitHub username/repository eg. "daattali/beautiful-jekyll"
# #  branch     : master # If you're not using `master` branch, then you also need to update the `branch` parameter in `staticman.yml`
# #  endpoint   : # URL of your deployment, with a trailing slash eg. "https://<your-api>/v3/entry/github/"
# #  reCaptcha:   # (optional, set these parameters in `staticman.yml` as well)
# #    siteKey  : # You need to apply for a site key on Google
# #    secret   : # Encrypt your password by going to https://<your-own-api>/v3/encrypt/<your-site-secret>

# # --- Misc --- #

# # Ruby Date Format to show dates of posts
# date_format: "%B %-d, %Y"
# # Facebook App ID
# #fb_app_id: ""
